# Generated by Django 4.2.11 on 2024-04-01 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peering", "0100_bgp_session_accepted_prefix_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="routingpolicy",
            old_name="type",
            new_name="direction",
        ),
    ]
