# Generated by Django 4.2.11 on 2024-04-01 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peering", "0101_rename_type_routingpolicy_direction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routingpolicy",
            name="communities",
        ),
    ]
