# Generated by Django 4.2.11 on 2024-04-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peering", "0102_remove_routingpolicy_communities"),
    ]

    operations = [
        migrations.AddField(
            model_name="routingpolicy",
            name="protocol",
            field=models.CharField(
                choices=[("bgp", "BGP"), ("ospf", "OSPF"), ("isis", "IS-IS")],
                default="bgp",
                max_length=50,
            ),
        ),
    ]
