# Generated by Django 4.2.11 on 2024-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peering", "0103_routingpolicy_protocol"),
    ]

    operations = [
        migrations.AddField(
            model_name="routingpolicy",
            name="type",
            field=models.CharField(
                choices=[("permit", "permit"), ("deny", "deny")],
                default="permit",
                max_length=50,
            ),
        ),
    ]
